# Generated by Django 5.1.5 on 2025-01-30 12:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_timetable_events_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timetable_events',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_events', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='timetable_events',
            name='event_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events_of_type', to='main.event_types'),
        ),
    ]
