# Generated by Django 5.1.5 on 2025-01-30 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_profile_first_name_alter_profile_last_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tasks',
            old_name='completed_status',
            new_name='completion_status',
        ),
        migrations.RenameField(
            model_name='tasks',
            old_name='end_date',
            new_name='due_date',
        ),
    ]
