# Generated by Django 5.1.7 on 2025-03-23 00:32

import main.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_tasks_due_date_alter_tasks_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to=main.models.user_profile_picture),
        ),
    ]
