# Generated by Django 5.1.7 on 2025-03-31 16:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_profile_profile_picture'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event_colors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_color', models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='timetable_events',
            name='event_color',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='events_of_color', to='main.event_colors'),
            preserve_default=False,
        ),
    ]
