# Generated by Django 5.1.7 on 2025-03-31 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_event_colors_timetable_events_event_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event_colors',
            name='event_color',
            field=models.CharField(max_length=6, unique=True),
        ),
    ]
