# Generated by Django 5.2.5 on 2025-08-30 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_alter_tasks_due_date_alter_tasks_event'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timetable_events',
            name='event_color',
            field=models.CharField(max_length=6),
        ),
        migrations.DeleteModel(
            name='Event_colors',
        ),
    ]
