# Generated by Django 5.2.5 on 2025-09-11 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_alter_timetable_events_event_color_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='timetable_events',
            name='do_notify',
            field=models.BooleanField(default=False),
        ),
    ]
